import { Song } from "./song";

export const allSongs: Song[] = [
    { id: 1, name: "Tim McGraw", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 2, name: "Picture To Burn", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 3, name: "Teardrops on My Guitar", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 4, name: "A Place in This World", album: "Taylor Swift", ranking: 8, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 5, name: "Cold as You", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 6, name: "The Outside", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 7, name: "Tied Together with a Smile", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 8, name: "Stay Beautiful", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 9, name: "Should've Said No", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 10, name: "Mary's Song (Oh My My My)", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 11, name: "Our Song", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 12, name: "I'm Only Me When I'm with You", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 13, name: "Invisible", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },
    { id: 14, name: "A Perfectly Good Heart", album: "Taylor Swift", ranking: undefined, genre: "Country", releaseYear: 2006, isFavorite:false },

    { id: 15, name: "Fearless", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 16, name: "Fifteen", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 17, name: "Love Story", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 18, name: "Hey Stephen", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 19, name: "White Horse", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 20, name: "You Belong with Me", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 21, name: "Breathe (featuring Colbie Caillat)", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 22, name: "Tell Me Why", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 23, name: "You're Not Sorry", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 24, name: "The Way I Loved You", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 25, name: "Forever & Always", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 26, name: "The Best Day", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 27, name: "Change", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 28, name: "Jump Then Fall", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 29, name: "Untouchable", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 30, name: "Come In with the Rain", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 31, name: "Superstar", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 32, name: "The Other Side of the Door", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 33, name: "Today Was a Fairytale", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 34, name: "You All Over Me (featuring Maren Morris)", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 35, name: "Mr. Perfectly Fine", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 36, name: "We Were Happy", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 37, name: "That's When (featuring Keith Urban)", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 38, name: "Don't You", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 39, name: "Bye Bye Baby", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },
    { id: 40, name: "If This Was A Movie", album: "Fearless", ranking: undefined, genre: "Country", releaseYear: 2008, isFavorite:false },

    { id: 41, name: "Mine", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 42, name: "Sparks Fly", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 43, name: "Back To December", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 44, name: "Speak Now", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 45, name: "Dear John", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 46, name: "Mean", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 47, name: "The Story Of Us", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 48, name: "Never Grow Up", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 49, name: "Enchanted", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 50, name: "Better Than Revenge", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 51, name: "Innocent", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 52, name: "Haunted", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 53, name: "Last Kiss", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 54, name: "Long Live", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 55, name: "Ours", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 56, name: "Superman", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 57, name: "Electric Touch (feat. Fall Out Boy)", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 58, name: "When Emma Falls in Love", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 59, name: "I Can See You", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 60, name: "Castles Crumbling (feat. Hayley Williams)", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 61, name: "Foolish One", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },
    { id: 62, name: "Timeless", album: "Speak Now", ranking: undefined, genre: "Country", releaseYear: 2010, isFavorite:false },

    { id: 63, name: "State Of Grace", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 64, name: "Red", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 65, name: "Treacherous", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 66, name: "I Knew You Were Trouble", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 67, name: "All Too Well", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 68, name: "22", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 69, name: "I Almost Do", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 70, name: "We Are Never Ever Getting Back Together", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 71, name: "Stay Stay Stay", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 72, name: "The Last Time (feat. Gary Lightbody)", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 73, name: "Holy Ground", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 74, name: "Sad Beautiful Tragic", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 75, name: "The Lucky One", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 76, name: "Everything Has Changed", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 77, name: "Starlight", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 78, name: "Begin Again", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 79, name: "The Moment I Knew", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 80, name: "Come Back...Be Here", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 81, name: "Girl At Home", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 82, name: "Ronan", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 83, name: "Better Man", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 84, name: "Nothing New (feat. Phoebe Bridgers)", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 85, name: "Babe", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 86, name: "Message In A Bottle", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 87, name: "I Bet You Think About Me (feat. Chris Stapleton)", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 88, name: "Forever Winter", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 89, name: "Run (feat. Ed Sheeran)", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 90, name: "The Very First Night", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },
    { id: 91, name: "All Too Well (10 Minute Version)", album: "Red", ranking: undefined, genre: "Pop", releaseYear: 2012, isFavorite:false },

    { id: 92, name: "Welcome To New York", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 93, name: "Blank Space", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 94, name: "Style", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 95, name: "Out Of The Woods", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 96, name: "All You Had To Do Was Stay", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 97, name: "Shake It Off", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 98, name: "I Wish You Would", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 99, name: "Bad Blood", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 100, name: "Wildest Dreams", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 101, name: "How You Get The Girl", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 102, name: "This Love", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 103, name: "I Know Places", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 104, name: "Clean", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 105, name: "Wonderland", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 106, name: "You Are In Love", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 107, name: "New Romantics", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 108, name: "Slut!", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 109, name: "Say Don't Go", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 110, name: "Now That We Don't Talk", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 111, name: "Suburban Legends", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },
    { id: 112, name: "Is It Over Now?", album: "1989", ranking: undefined, genre: "Pop", releaseYear: 2014, isFavorite:false },

    { id: 113, name: "...Ready For It", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 114, name: "End Game", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 115, name: "I Did Something Bad", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 116, name: "Don't Blame Me", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 117, name: "Delicate", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 118, name: "Look What You Made Me Do", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 119, name: "So It Goes...", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 120, name: "Gorgeous", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 121, name: "Getaway Car", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 122, name: "King Of My Heart", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 123, name: "Dancing With Our Hands Tied", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 124, name: "Dress", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 125, name: "This Is Why We Can't Have Nice Things", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 126, name: "Call It What You Want", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },
    { id: 127, name: "New Year's Day", album: "Reputation", ranking: undefined, genre: "Pop", releaseYear: 2017, isFavorite:false },

    { id: 128, name: "I Forgot That You Existed", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 129, name: "Cruel Summer", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 130, name: "Lover", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 131, name: "The Man", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 132, name: "The Archer", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 133, name: "I Think He Knows", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 134, name: "Miss Americana & The Heartbreak Prince", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 135, name: "Paper Rings", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 136, name: "Cornelia Street", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 137, name: "Death By A Thousand Cuts", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 138, name: "London Boy", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 139, name: "Soon You'll Get Better (feat. The Chicks)", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 140, name: "False God", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 141, name: "You Need To Calm Down", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 142, name: "Afterglow", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 143, name: "ME!", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 144, name: "It's Nice To Have A Friend", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 145, name: "Daylight", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },
    { id: 146, name: "All Of The Girls You Loved Before", album: "Lover", ranking: undefined, genre: "Pop", releaseYear: 2019, isFavorite:false },                                      

    { id: 147, name: "the 1", album: "Folklore", ranking: undefined, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 148, name: "cardigan", album: "Folklore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 149, name: "the last great american dynasty", album: "Folklore", ranking: 9, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 150, name: "exile (feat. Bon Iver)", album: "Folklore", ranking: 9, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 151, name: "my tears ricochet", album: "Folklore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 152, name: "mirrorball", album: "Folklore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 153, name: "seven", album: "Folklore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 154, name: "august", album: "Folklore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 155, name: "this is me trying", album: "Folklore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 156, name: "illicit affairs", album: "Folklore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 157, name: "invisible string", album: "Folklore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 158, name: "mad woman", album: "Folklore", ranking: 9, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 159, name: "epiphany", album: "Folklore", ranking: 4, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 160, name: "betty", album: "Folklore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 161, name: "peace", album: "Folklore", ranking: 5, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 162, name: "hoax", album: "Folklore", ranking: 8, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 163, name: "the lakes", album: "Folklore", ranking: 8, genre: "Alternative", releaseYear: 2020, isFavorite:false },

    { id: 164, name: "willow", album: "Evermore", ranking: 8, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 165, name: "champagne problems", album: "Evermore", ranking: 9, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 166, name: "gold rush", album: "Evermore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 167, name: "'tis the damn season", album: "Evermore", ranking: 8, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 168, name: "tolerate it", album: "Evermore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 169, name: "no body, no crime (feat. HAIM)", album: "Evermore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 170, name: "happiness", album: "Evermore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 171, name: "dorothea", album: "Evermore", ranking: 4, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 172, name: "coney island (feat. The National)", album: "Evermore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 173, name: "ivy", album: "Evermore", ranking: 7, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 174, name: "cowboy like me", album: "Evermore", ranking: 9, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 175, name: "long story short", album: "Evermore", ranking: 8, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 176, name: "marjorie", album: "Evermore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 177, name: "closure", album: "Evermore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 178, name: "evermore (feat. Bon Iver)", album: "Evermore", ranking: 4, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 179, name: "right where you left me", album: "Evermore", ranking: 10, genre: "Alternative", releaseYear: 2020, isFavorite:false },
    { id: 180, name: "it's time to go", album: "Evermore", ranking: 6, genre: "Alternative", releaseYear: 2020, isFavorite:false },

    { id: 181, name: "Lavender Haze", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 182, name: "Maroon", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 183, name: "Anti-Hero", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 184, name: "Snow On The Beach (feat. Lana Del Ray)", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 185, name: "You're On Your Own, Kid", album: "Midnights", ranking: 9, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 186, name: "Midnight Rain", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 187, name: "Question...?", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 188, name: "Vigilante Shit", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 189, name: "Bejeweled", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 190, name: "Labyrinth", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 191, name: "Karma", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 192, name: "Sweet Nothing", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 193, name: "Mastermind", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 194, name: "The Great War", album: "Midnights", ranking: 9, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 195, name: "Bigger Than The Whole Sky", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 196, name: "Paris", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 197, name: "High Infidelity ", album: "Midnights", ranking: 9, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 198, name: "Glitch", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 199, name: "Would've, Could've, Should've", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 200, name: "Dear Reader", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 201, name: "Hits Different", album: "Midnights", ranking: undefined, genre: "Pop", releaseYear: 2022, isFavorite:false },
    { id: 202, name: "You're Losing Me", album: "Midnights", ranking: 7, genre: "Pop", releaseYear: 2022, isFavorite:false },

    { id: 203, name: "Renegade", album: "misc", ranking: undefined, genre: "Alternative", releaseYear: 2021, isFavorite:false },
    { id: 204, name: "Carolina", album: "misc", ranking: undefined, genre: "Soundtrack", releaseYear: 2022, isFavorite:false },
    { id: 205, name: "The Alcott (feat. Taylor Swift)", album: "misc", ranking: undefined, genre: "Alternative", releaseYear: 2023, isFavorite:false },
];